
# 7.1 异常概述与异常体系结构

![title](https://raw.githubusercontent.com/XJZ-0707/imge/master/gitnote/2019/09/24/%E5%BC%82%E5%B8%B8%E5%8E%9F%E5%9B%A0-1569293452289.jpg)

![title](https://raw.githubusercontent.com/XJZ-0707/imge/master/gitnote/2019/09/24/%E5%BC%82%E5%B8%B8-1569293526714.jpg)
![title](https://raw.githubusercontent.com/XJZ-0707/imge/master/gitnote/2019/09/24/%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB-1569294477301.jpg)

![title](https://raw.githubusercontent.com/XJZ-0707/imge/master/gitnote/2019/09/24/%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB2-1569294564438.jpg)


## Java虚拟机无法解决的严重问题
```java 
package com.day16.java;
/*
 * Error:
 * Java虚拟机无法解决的严重问题。如：JVM系统内部错误、资源耗尽等严重情况。比如：StackOverflowError和OOM。
 * 
 * 一般不编写针对性的代码进行处理。
 * 
 * 
 */
public class ErrorTest {
	public static void main(String[] args) {
		//1.栈溢出：java.lang.StackOverflowError
//		main(args);
		//2.堆溢出：java.lang.OutOfMemoryError 
		Integer[] arr = new Integer[1024*1024*1024];
	}
}

```


# 7.2 常见异常
```java
package com.day16.java1;

import java.util.Date;
import java.util.Scanner;

import org.junit.Test;

/*
 * 一、异常体系结构
 * 
 * java.lang.Throwable
 * 		|-----java.lang.Error:一般不编写针对性的代码进行处理。
 * 		|-----java.lang.Exception:可以进行异常的处理
 * 			|------编译时异常(checked)
 * 					|-----IOException
 * 						|-----FileNotFoundException （文件未找到）
 * 					|-----ClassNotFoundException（类未找到）
 * 			|------运行时异常(unchecked,RuntimeException)
 * 					|-----NullPointerException（空指针异常）
 * 					|-----ArrayIndexOutOfBoundsException（数组角标异常）
 * 					|-----ClassCastException（类转换异常）
 * 					|-----NumberFormatException（数提交异常）
 * 					|-----InputMismatchException（输入）
 * 					|-----ArithmeticException
 * 
 * 
 * 
 * 面试题：常见的异常都有哪些？举例说明
 */
public class ExceptionTest {
	
	//******************以下是编译时异常***************************
	@Test
	public void test7(){
//		File file = new File("hello.txt");
//		FileInputStream fis = new FileInputStream(file);
//		
//		int data = fis.read();
//		while(data != -1){
//			System.out.print((char)data);
//			data = fis.read();
//		}
//		
//		fis.close();
		
	}
	
	//******************以下是运行时异常***************************
	//ArithmeticException
	@Test
	public void test6(){
		int a = 10;
		int b = 0;
		System.out.println(a / b);
	}
	
	//InputMismatchException
	@Test
	public void test5(){
		Scanner scanner = new Scanner(System.in);
		int score = scanner.nextInt();
		System.out.println(score);
		
		scanner.close();
	}
	
	//NumberFormatException
	@Test
	public void test4(){
		
		String str = "123";
		str = "abc";
		int num = Integer.parseInt(str);
		
		
		
	}
	
	//ClassCastException
	@Test
	public void test3(){
		Object obj = new Date();
		String str = (String)obj;
	}
	
	//IndexOutOfBoundsException
	@Test
	public void test2(){
		//ArrayIndexOutOfBoundsException
//		int[] arr = new int[10];
//		System.out.println(arr[10]);
		//StringIndexOutOfBoundsException
		String str = "abc";
		System.out.println(str.charAt(3));
	}
	
	//NullPointerException
	@Test
	public void test1(){
		
//		int[] arr = null;
//		System.out.println(arr[3]);
		
		String str = "abc";
		str = null;
		System.out.println(str.charAt(0));
		
	}
	
	
}

```


# 7.3 异常处理机制一：try-catch-finally


# 7.4 异常处理机制二：throws


# 7.5 手动抛出异常：throw


# 7.6 用户自定义异常类
